apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sample-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sample-react-app
  template:
    metadata:
      labels:
        app: my-sample-react-app
    spec:
      containers:
      - name: my-sample-react-container
        image: asia-southeast2-docker.pkg.dev/our-hull-385315/my-sample-react-app-repo/my-sample-react-app:${IMAGE_TAG}
        ports:
        - containerPort: 80