apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: LoadBalancer # Using LoadBalancer to expose the service externally
  selector:
    app: react-app
  ports:
    - port: 80
      targetPort: 80